- name: Deploy NFD operator
  k8s:
    definition: "{{ lookup('template', 'nfd-subscription.yaml') }}"

- name: Wait for NFD operator to deploy
  import_role:
    name: common_tasks
    tasks_from: wait_for_operator.yml
  vars:
    operator_name: nfd
    operator_namespace: openshift-operators

- name: Deploy NFD instance
  k8s:
    definition: "{{ lookup('template', '{{ item }}') }}"
  loop:
    - nfd-namespace.yaml
    - nfd-master-server-nodefeaturediscovery.yaml
