#rhel_entitlements_cert: |
#  -----BEGIN RSA PRIVATE KEY-----
#  MIIJKgIBAAKCAgEA2Ie0f+xfmpDfeRpZDNijOWYNSK/WMJK38X8zxOg1/Y2+d/6O
#  pZ25taaqz5mgS15+r4iK/QLFP7Cn/+30p+2dGUfMU3zLbEMl0jNkj8P5gtK2/59C
#  ...

#rhel_entitlements_key: |
#  -----BEGIN CERTIFICATE-----
#  MIIcMDCCGhigAwIBAgIIR0jdX8pNLMAwDQYJKoZIhvcNAQELBQAwgaQxCzAJBgNV
#  BAYTAlVTMRcwFQYDVQQIDA5Ob3J0aCBDYXJvbGluYTEWMBQGA1UECgwNUmVkIEhh
#  ...
