- name: Waiting since {{ lookup("pipe", "date +%r") }} for CSV to appear
  k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: '{{ operator_name }}'
    namespace: '{{ operator_namespace }}'
  register: operator_subscription
  until:
    - operator_subscription.resources.0.status is defined
    - operator_subscription.resources.0.status.currentCSV is defined
  failed_when: False
  retries: 60
  delay: 10

- name: Waiting since {{ lookup("pipe", "date +%r") }} for the operator to deploy
  k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    name: '{{ operator_subscription.resources.0.status.currentCSV }}'
    namespace: '{{ operator_namespace }}'
  register: operator_csv
  until:
    - operator_csv.resources.0.status is defined
    - operator_csv.resources.0.status.phase is defined
    - operator_csv.resources.0.status.phase == 'Succeeded'
  failed_when: False
  retries: 60
  delay: 10