- name: Deploy GPU operator
  k8s:
    definition: "{{ lookup('template', '{{ item }}') }}"
  loop:
    - gpu-operator-namespace.yaml
    - gpu-operator-operatorgroup.yaml
    - gpu-operator-subscription.yaml

- name: Wait for GPU operator to deploy
  import_role:
    name: common_tasks
    tasks_from: wait_for_operator.yml
  vars:
    operator_name: gpu-operator
    operator_namespace: '{{ gpu_namespace }}'

- name: Deploy GPU instance
  k8s:
    definition: "{{ lookup('template', 'nvidia-gpu-clusterpolicy.yaml') }}"
