- name: Waiting since {{ lookup("pipe", "date +%r") }} for pod {{ pod_name }} to complete
  k8s_info:
    api_version: v1
    kind: Pod
    name: '{{ pod_name }}'
    namespace: '{{ pod_namespace }}'
  register: pod_info
  until:
    - pod_info.resources.0.status is defined
    - pod_info.resources.0.status.conditions is defined
    - pod_info.resources.0.status.conditions | selectattr('type', 'equalto', 'Ready') | list | length > 0
    - (pod_info.resources.0.status.conditions | selectattr('type', 'equalto', 'Ready') | list | first).reason == 'PodCompleted'
  failed_when: False
  retries: 60
  delay: 10